### ISSUE TITLE
`ansiblediscover.graph` is not a package

### ISSUE THREAD

**Issue by uSpike** [croesnick/ansible-discover#12]
`ansiblediscover/graph` is a directory, and to be a python package it must contain a `__init__.py`.  Without this, it is not being discovered by `setuptools.find_packages` and thus:

```
$ pip install ansible-discover
...
Successfully installed ansible-discover-0.1.0 ruamel.yaml-0.15.54
$ ansible-discover 
Traceback (most recent call last):
  File "/home/me/src/molecule/ansible-playbooks/venv/bin/ansible-discover", line 7, in <module>
    from ansiblediscover.cli import cli
  File "/home/me/src/molecule/ansible-playbooks/venv/lib/python3.6/site-packages/ansiblediscover/cli.py", line 8, in <module>
    from ansiblediscover.graph.dependencies import Dependencies
ModuleNotFoundError: No module named 'ansiblediscover.graph'
```

**Comment by uSpike** [comment]
The same is true for `utils`.
